/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'account-invitations': AccountInvitation;
    'security-audit-events': SecurityAuditEvent;
    media: Media;
    'retreat-events': RetreatEvent;
    'model-profiles': ModelProfile;
    'photographer-profiles': PhotographerProfile;
    'model-applications': ModelApplication;
    'photographer-applications': PhotographerApplication;
    'artist-availability': ArtistAvailability;
    'retreat-bookings': RetreatBooking;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'account-invitations': AccountInvitationsSelect<false> | AccountInvitationsSelect<true>;
    'security-audit-events': SecurityAuditEventsSelect<false> | SecurityAuditEventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'retreat-events': RetreatEventsSelect<false> | RetreatEventsSelect<true>;
    'model-profiles': ModelProfilesSelect<false> | ModelProfilesSelect<true>;
    'photographer-profiles': PhotographerProfilesSelect<false> | PhotographerProfilesSelect<true>;
    'model-applications': ModelApplicationsSelect<false> | ModelApplicationsSelect<true>;
    'photographer-applications': PhotographerApplicationsSelect<false> | PhotographerApplicationsSelect<true>;
    'artist-availability': ArtistAvailabilitySelect<false> | ArtistAvailabilitySelect<true>;
    'retreat-bookings': RetreatBookingsSelect<false> | RetreatBookingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Applies only to administrator accounts.
   */
  role?: ('owner' | 'editor' | 'reviewer') | null;
  /**
   * Only an owner may assign or change account roles.
   */
  roles: ('administrator' | 'photographer' | 'model')[];
  /**
   * Invited and suspended accounts cannot access protected platform features.
   */
  accountStatus: 'invited' | 'active' | 'suspended';
  invitedAt?: string | null;
  invitationAcceptedAt?: string | null;
  lastLoginAt?: string | null;
  suspendedAt?: string | null;
  suspensionReason?: string | null;
  /**
   * Incremented when access should be revoked. Existing Payload sessions are cleared when an account is suspended.
   */
  sessionVersion?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Invitation-only account activation records. Raw activation tokens are never stored.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-invitations".
 */
export interface AccountInvitation {
  id: number;
  email: string;
  roles: ('administrator' | 'photographer' | 'model')[];
  /**
   * Only applies when the invitation includes administrator access.
   */
  staffPermission?: ('owner' | 'editor' | 'reviewer') | null;
  status: 'pending' | 'accepted' | 'revoked' | 'expired';
  tokenHash: string;
  tokenExpiresAt: string;
  invitedBy?: (number | null) | User;
  acceptedAccount?: (number | null) | User;
  acceptedAt?: string | null;
  revokedAt?: string | null;
  relatedModelProfile?: (number | null) | ModelProfile;
  relatedPhotographerProfile?: (number | null) | PhotographerProfile;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Canonical model records. Event participation will reference these profiles rather than duplicate them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-profiles".
 */
export interface ModelProfile {
  id: number;
  /**
   * Optional one-to-one authentication owner. Applications never set this automatically.
   */
  account?: (number | null) | User;
  displayName: string;
  slug: string;
  approvalStatus: 'draft' | 'review' | 'approved' | 'archived';
  publicIntroduction?: string | null;
  biography?: string | null;
  artistStatement?: string | null;
  featuredImage?: (number | null) | Media;
  portfolioImages?: (number | Media)[] | null;
  modelingCategories?:
    ('glamour' | 'boudoir' | 'fashion' | 'editorial' | 'fine-art' | 'lifestyle' | 'commercial')[] | null;
  city?: string | null;
  state?: string | null;
  website?: string | null;
  instagram?: string | null;
  usagePermissionConfirmed?: boolean | null;
  /**
   * Every option is private by default. Enable only after the artist has approved that information for public display.
   */
  publicDisplay?: {
    biography?: boolean | null;
    artistStatement?: boolean | null;
    location?: boolean | null;
    categories?: boolean | null;
    instagram?: boolean | null;
    website?: boolean | null;
  };
  adminNotes?: string | null;
  /**
   * Private scheduling preferences. Contact details are shared only after a confirmed booking and only when explicitly approved here.
   */
  bookingPreferences?: {
    /**
     * Required before this participant can be used in a confirmed booking.
     */
    email?: string | null;
    mobilePhone?: string | null;
    shareEmail?: boolean | null;
    shareInstagram?: boolean | null;
    shareMobilePhone?: boolean | null;
    shareWebsite?: boolean | null;
    notifyByEmail?: boolean | null;
    notifyBySms?: boolean | null;
    notifyInDashboard?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  usageApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Canonical photographer records. Registrations and event participation will reference these profiles later.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photographer-profiles".
 */
export interface PhotographerProfile {
  id: number;
  /**
   * Optional one-to-one authentication owner. Applications never set this automatically.
   */
  account?: (number | null) | User;
  displayName: string;
  slug: string;
  approvalStatus: 'draft' | 'review' | 'approved' | 'archived';
  publicIntroduction?: string | null;
  biography?: string | null;
  profileImage?: (number | null) | Media;
  experienceLevel?: ('developing' | 'intermediate' | 'advanced' | 'professional') | null;
  equipmentSummary?: string | null;
  city?: string | null;
  state?: string | null;
  website?: string | null;
  instagram?: string | null;
  adminNotes?: string | null;
  /**
   * Private scheduling preferences. Contact details are shared only after a confirmed booking and only when explicitly approved here.
   */
  bookingPreferences?: {
    /**
     * Required before this participant can be used in a confirmed booking.
     */
    email?: string | null;
    mobilePhone?: string | null;
    shareEmail?: boolean | null;
    shareInstagram?: boolean | null;
    shareMobilePhone?: boolean | null;
    shareWebsite?: boolean | null;
    notifyByEmail?: boolean | null;
    notifyBySms?: boolean | null;
    notifyInDashboard?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Immutable security history for account lifecycle, role, status, invitation, and protected-access events.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-audit-events".
 */
export interface SecurityAuditEvent {
  id: number;
  eventType: string;
  severity: 'info' | 'warning' | 'critical';
  actor?: (number | null) | User;
  targetAccount?: (number | null) | User;
  targetInvitation?: (number | null) | AccountInvitation;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retreat-events".
 */
export interface RetreatEvent {
  id: number;
  title: string;
  slug: string;
  lifecycleStatus: 'draft' | 'prototype' | 'published' | 'closed' | 'archived';
  summary: string;
  heroImage?: (number | null) | Media;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * IANA time zone used for availability and booking calculations, for example America/Chicago.
   */
  timeZone: string;
  locationName?: string | null;
  locationDetails?: string | null;
  capacity?: number | null;
  registrationStatus: 'coming-soon' | 'applications-open' | 'registration-open' | 'waitlist' | 'closed';
  /**
   * Event-specific artist assignments. Only approved assignments whose master profiles and media are also published and approved may appear publicly.
   */
  participatingArtists?:
    | {
        artist: number | ModelProfile;
        participationStatus: 'invited' | 'confirmed' | 'approved' | 'withdrawn';
        displayOrder?: number | null;
        minimumBookingHours: '1' | '2' | '3';
        id?: string | null;
      }[]
    | null;
  /**
   * Event-specific photographer access. Only approved participants are eligible for confirmed bookings.
   */
  participatingPhotographers?:
    | {
        photographer: number | PhotographerProfile;
        participationStatus: 'invited' | 'registered' | 'approved' | 'withdrawn';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Private review inbox. Review the application, accept/decline it, then create a private draft Featured Model profile when you are ready. Nothing publishes automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-applications".
 */
export interface ModelApplication {
  id: number;
  /**
   * Choose where this application stands: New, Reviewing, Accepted, Declined, or Waitlist. This only updates your private review status; it does not publish anything.
   */
  applicationStatus: 'new' | 'reviewing' | 'accepted' | 'declined' | 'waitlist';
  /**
   * Use this when you want to keep reviewing before anything can appear publicly. Check this box and save. The system copies the application into a private draft Featured Model profile.
   */
  createProfileFromApplication?: boolean | null;
  /**
   * Use this when the applicant is accepted and ready to appear publicly. Check this box and save once. The system creates or updates the Featured Model profile, approves the submitted profile image for platform use, publishes the profile, adds the artist to the Founders Edition retreat, and approves that event assignment for public display.
   */
  approveForFoundersEdition?: boolean | null;
  /**
   * This is a receipt, not a task. If it shows a name, the Featured Model profile exists. If you used the public lineup approval above, the profile and Founders Edition event assignment are handled automatically.
   */
  linkedModelProfile?: (number | null) | ModelProfile;
  privateAdminNotes?: string | null;
  /**
   * Private review image submitted by the applicant. Nothing is published unless a media item is explicitly approved for platform use later.
   */
  preferredHeroImage?: (number | null) | Media;
  /**
   * Private review images submitted by the applicant. Nothing is published automatically.
   */
  additionalPortfolioImages?: (number | Media)[] | null;
  /**
   * Private administrative information. Never display publicly. It may be collected later for contracts, payment, or tax documentation.
   */
  legalName?: string | null;
  stageName: string;
  email: string;
  phone: string;
  city: string;
  state: string;
  country: string;
  instagramURL?: string | null;
  websiteURL?: string | null;
  portfolioURL?: string | null;
  agencyRepresentation?: string | null;
  marketingSource:
    | 'instagram'
    | 'facebook'
    | 'friend'
    | 'photographer'
    | 'model'
    | 'workshop'
    | 'magazine'
    | 'google-search'
    | 'other';
  otherMarketingSource?: string | null;
  modelingExperienceLevel: 'aspiring' | 'developing' | 'experienced' | 'professional';
  /**
   * Legacy storage field. The public application records the applicant-facing Travel Commitment answer in Travel / availability notes.
   */
  travelAvailability: 'local-only' | 'regional' | 'domestic' | 'international' | 'case-by-case';
  homeAirport?: string | null;
  availabilityNotes?: string | null;
  /**
   * Version 1 availability overview. The public form requires this on new applications. Older verification records may be blank; if so, do not let this block review.
   */
  creativeInterests?:
    | (
        | 'fashion'
        | 'editorial'
        | 'glamour'
        | 'swimwear'
        | 'lingerie'
        | 'boudoir'
        | 'artistic-nude'
        | 'fine-art-nude'
        | 'beauty'
        | 'conceptual-creative'
        | 'lifestyle'
        | 'other'
      )[]
    | null;
  otherCreativeInterest?: string | null;
  retreatGoals?:
    | (
        | 'network-with-photographers'
        | 'long-term-collaborations'
        | 'paid-shooting-opportunities'
        | 'expand-portfolio'
        | 'publication-opportunities'
        | 'professional-event-travel'
        | 'meet-professional-models'
        | 'professional-respectful-photographers'
        | 'other'
      )[]
    | null;
  otherRetreatGoal?: string | null;
  shortBiography: string;
  artistStatement?: string | null;
  informationAccurateConfirmed: boolean;
  noAcceptanceGuaranteeConfirmed: boolean;
  consentImageUsageConfirmed: boolean;
  codeOfConductConfirmed: boolean;
  contactPermissionConfirmed: boolean;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private review inbox. Review the application, accept/decline it, then connect it to a private photographer profile when you are ready. Nothing publishes automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photographer-applications".
 */
export interface PhotographerApplication {
  id: number;
  /**
   * Choose where this application stands: New, Reviewing, Accepted, Declined, or Waitlist. This only updates your private review status; it does not publish anything.
   */
  applicationStatus: 'new' | 'reviewing' | 'accepted' | 'declined' | 'waitlist';
  /**
   * Use this after review if this application belongs with an existing private photographer profile. Nothing is published automatically.
   */
  linkedPhotographerProfile?: (number | null) | PhotographerProfile;
  privateAdminNotes?: string | null;
  legalName: string;
  displayName?: string | null;
  email: string;
  phone: string;
  city: string;
  state: string;
  country: string;
  instagramURL?: string | null;
  websiteURL?: string | null;
  portfolioURL?: string | null;
  marketingSource:
    | 'instagram'
    | 'facebook'
    | 'friend'
    | 'photographer'
    | 'model'
    | 'workshop'
    | 'magazine'
    | 'google-search'
    | 'other';
  otherMarketingSource?: string | null;
  photographyExperienceLevel: 'developing' | 'intermediate' | 'advanced' | 'professional';
  equipmentSummary?: string | null;
  genresInterests: (
    'glamour' | 'boudoir' | 'editorial' | 'artistic-nude' | 'fashion' | 'swimwear' | 'beauty' | 'other'
  )[];
  otherGenreInterest?: string | null;
  whatTheyHopeToCreate: string;
  retreatGoals: string;
  collaborationStyleNotes?: string | null;
  informationAccurateConfirmed: boolean;
  noAcceptanceGuaranteeConfirmed: boolean;
  internalImageReviewConfirmed: boolean;
  codeOfConductConfirmed: boolean;
  contactPermissionConfirmed: boolean;
  submittedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private event-specific availability. Confirmed booking time cannot be blocked or removed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-availability".
 */
export interface ArtistAvailability {
  id: number;
  event: number | RetreatEvent;
  artist: number | ModelProfile;
  date: string;
  availableFrom: string;
  availableUntil: string;
  blockedTimes?:
    | {
        startTime: string;
        endTime: string;
        reason: 'unavailable' | 'lunch' | 'other';
        privateNote?: string | null;
        id?: string | null;
      }[]
    | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private operational reservations. Public and participant schedule views must use a separate allowlisted projection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retreat-bookings".
 */
export interface RetreatBooking {
  id: number;
  event: number | RetreatEvent;
  artist: number | ModelProfile;
  photographer: number | PhotographerProfile;
  startAt: string;
  endAt: string;
  status: 'confirmed' | 'cancelled' | 'rescheduled' | 'admin-review';
  rescheduledFrom?: (number | null) | RetreatBooking;
  /**
   * Allows an authorized administrator to place a booking outside stated availability. It never permits double-booking.
   */
  adminOverride?: boolean | null;
  exceptionReason?: string | null;
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'account-invitations';
        value: number | AccountInvitation;
      } | null)
    | ({
        relationTo: 'security-audit-events';
        value: number | SecurityAuditEvent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'retreat-events';
        value: number | RetreatEvent;
      } | null)
    | ({
        relationTo: 'model-profiles';
        value: number | ModelProfile;
      } | null)
    | ({
        relationTo: 'photographer-profiles';
        value: number | PhotographerProfile;
      } | null)
    | ({
        relationTo: 'model-applications';
        value: number | ModelApplication;
      } | null)
    | ({
        relationTo: 'photographer-applications';
        value: number | PhotographerApplication;
      } | null)
    | ({
        relationTo: 'artist-availability';
        value: number | ArtistAvailability;
      } | null)
    | ({
        relationTo: 'retreat-bookings';
        value: number | RetreatBooking;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  roles?: T;
  accountStatus?: T;
  invitedAt?: T;
  invitationAcceptedAt?: T;
  lastLoginAt?: T;
  suspendedAt?: T;
  suspensionReason?: T;
  sessionVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "account-invitations_select".
 */
export interface AccountInvitationsSelect<T extends boolean = true> {
  email?: T;
  roles?: T;
  staffPermission?: T;
  status?: T;
  tokenHash?: T;
  tokenExpiresAt?: T;
  invitedBy?: T;
  acceptedAccount?: T;
  acceptedAt?: T;
  revokedAt?: T;
  relatedModelProfile?: T;
  relatedPhotographerProfile?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "security-audit-events_select".
 */
export interface SecurityAuditEventsSelect<T extends boolean = true> {
  eventType?: T;
  severity?: T;
  actor?: T;
  targetAccount?: T;
  targetInvitation?: T;
  metadata?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  usageApproved?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retreat-events_select".
 */
export interface RetreatEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lifecycleStatus?: T;
  summary?: T;
  heroImage?: T;
  startDate?: T;
  endDate?: T;
  timeZone?: T;
  locationName?: T;
  locationDetails?: T;
  capacity?: T;
  registrationStatus?: T;
  participatingArtists?:
    | T
    | {
        artist?: T;
        participationStatus?: T;
        displayOrder?: T;
        minimumBookingHours?: T;
        id?: T;
      };
  participatingPhotographers?:
    | T
    | {
        photographer?: T;
        participationStatus?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-profiles_select".
 */
export interface ModelProfilesSelect<T extends boolean = true> {
  account?: T;
  displayName?: T;
  slug?: T;
  approvalStatus?: T;
  publicIntroduction?: T;
  biography?: T;
  artistStatement?: T;
  featuredImage?: T;
  portfolioImages?: T;
  modelingCategories?: T;
  city?: T;
  state?: T;
  website?: T;
  instagram?: T;
  usagePermissionConfirmed?: T;
  publicDisplay?:
    | T
    | {
        biography?: T;
        artistStatement?: T;
        location?: T;
        categories?: T;
        instagram?: T;
        website?: T;
      };
  adminNotes?: T;
  bookingPreferences?:
    | T
    | {
        email?: T;
        mobilePhone?: T;
        shareEmail?: T;
        shareInstagram?: T;
        shareMobilePhone?: T;
        shareWebsite?: T;
        notifyByEmail?: T;
        notifyBySms?: T;
        notifyInDashboard?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photographer-profiles_select".
 */
export interface PhotographerProfilesSelect<T extends boolean = true> {
  account?: T;
  displayName?: T;
  slug?: T;
  approvalStatus?: T;
  publicIntroduction?: T;
  biography?: T;
  profileImage?: T;
  experienceLevel?: T;
  equipmentSummary?: T;
  city?: T;
  state?: T;
  website?: T;
  instagram?: T;
  adminNotes?: T;
  bookingPreferences?:
    | T
    | {
        email?: T;
        mobilePhone?: T;
        shareEmail?: T;
        shareInstagram?: T;
        shareMobilePhone?: T;
        shareWebsite?: T;
        notifyByEmail?: T;
        notifyBySms?: T;
        notifyInDashboard?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-applications_select".
 */
export interface ModelApplicationsSelect<T extends boolean = true> {
  applicationStatus?: T;
  createProfileFromApplication?: T;
  approveForFoundersEdition?: T;
  linkedModelProfile?: T;
  privateAdminNotes?: T;
  preferredHeroImage?: T;
  additionalPortfolioImages?: T;
  legalName?: T;
  stageName?: T;
  email?: T;
  phone?: T;
  city?: T;
  state?: T;
  country?: T;
  instagramURL?: T;
  websiteURL?: T;
  portfolioURL?: T;
  agencyRepresentation?: T;
  marketingSource?: T;
  otherMarketingSource?: T;
  modelingExperienceLevel?: T;
  travelAvailability?: T;
  homeAirport?: T;
  availabilityNotes?: T;
  creativeInterests?: T;
  otherCreativeInterest?: T;
  retreatGoals?: T;
  otherRetreatGoal?: T;
  shortBiography?: T;
  artistStatement?: T;
  informationAccurateConfirmed?: T;
  noAcceptanceGuaranteeConfirmed?: T;
  consentImageUsageConfirmed?: T;
  codeOfConductConfirmed?: T;
  contactPermissionConfirmed?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photographer-applications_select".
 */
export interface PhotographerApplicationsSelect<T extends boolean = true> {
  applicationStatus?: T;
  linkedPhotographerProfile?: T;
  privateAdminNotes?: T;
  legalName?: T;
  displayName?: T;
  email?: T;
  phone?: T;
  city?: T;
  state?: T;
  country?: T;
  instagramURL?: T;
  websiteURL?: T;
  portfolioURL?: T;
  marketingSource?: T;
  otherMarketingSource?: T;
  photographyExperienceLevel?: T;
  equipmentSummary?: T;
  genresInterests?: T;
  otherGenreInterest?: T;
  whatTheyHopeToCreate?: T;
  retreatGoals?: T;
  collaborationStyleNotes?: T;
  informationAccurateConfirmed?: T;
  noAcceptanceGuaranteeConfirmed?: T;
  internalImageReviewConfirmed?: T;
  codeOfConductConfirmed?: T;
  contactPermissionConfirmed?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-availability_select".
 */
export interface ArtistAvailabilitySelect<T extends boolean = true> {
  event?: T;
  artist?: T;
  date?: T;
  availableFrom?: T;
  availableUntil?: T;
  blockedTimes?:
    | T
    | {
        startTime?: T;
        endTime?: T;
        reason?: T;
        privateNote?: T;
        id?: T;
      };
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retreat-bookings_select".
 */
export interface RetreatBookingsSelect<T extends boolean = true> {
  event?: T;
  artist?: T;
  photographer?: T;
  startAt?: T;
  endAt?: T;
  status?: T;
  rescheduledFrom?: T;
  adminOverride?: T;
  exceptionReason?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'retreat-events';
          value: number | RetreatEvent;
        } | null)
      | ({
          relationTo: 'model-profiles';
          value: number | ModelProfile;
        } | null)
      | ({
          relationTo: 'photographer-profiles';
          value: number | PhotographerProfile;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}